
import { ServiceItem, ClientInfo, ProposalConfig } from './types';

export const INITIAL_SERVICES: ServiceItem[] = [
  // --- 1. Content & Creative ---
  {
    id: 'bc-web-1',
    category: 'Content & Creative',
    subcategory: 'Brand Creatives - Website',
    name: 'Website Banner',
    unit: 'Per Banner',
    price: 500,
    deliverables: 'Website banner (standard resolution)',
    active: true,
  },
  {
    id: 'bc-web-2',
    category: 'Content & Creative',
    subcategory: 'Brand Creatives - Website',
    name: 'Mobile Banner',
    unit: 'Per Banner',
    price: 250,
    deliverables: 'Mobile view banner',
    active: true,
  },
  {
    id: 'bc-web-3',
    category: 'Content & Creative',
    subcategory: 'Brand Creatives - Website',
    name: 'Infographic Image',
    unit: 'Per Image',
    price: 150,
    deliverables: 'Infographic design',
    active: true,
  },
  {
    id: 'bc-mp-1',
    category: 'Content & Creative',
    subcategory: 'Brand Creatives - Marketplace',
    name: 'Marketplace EBC',
    unit: 'Per Banner',
    price: 500,
    deliverables: 'Enhanced Brand Content',
    active: true,
  },
  {
    id: 'bc-mp-2',
    category: 'Content & Creative',
    subcategory: 'Brand Creatives - Marketplace',
    name: 'Brand Store',
    unit: 'Per Banner',
    price: 800,
    deliverables: 'Brand store creative',
    active: true,
  },
  {
    id: 'bc-sm-1',
    category: 'Content & Creative',
    subcategory: 'Brand Creatives - Social Media',
    name: 'SMO Post',
    unit: 'Per Post',
    price: 350,
    deliverables: '1 carousel post (Additional image: ₹100)',
    active: true,
  },
  {
    id: 'bc-sm-2',
    category: 'Content & Creative',
    subcategory: 'Brand Creatives - Social Media',
    name: 'SMO Stories',
    unit: 'Per Story',
    price: 250,
    deliverables: '1 image',
    active: true,
  },
  {
    id: 'bc-sm-3',
    category: 'Content & Creative',
    subcategory: 'Brand Creatives - Social Media',
    name: 'SMO Reel',
    unit: 'Per Reel',
    price: 500,
    deliverables: '1 reel video (Up to 20 sec)',
    active: true,
  },
  {
    id: 'bc-br-1',
    category: 'Content & Creative',
    subcategory: 'Brand Creatives - Branding',
    name: 'Brochure (5 Pages)',
    unit: '5 Pages',
    price: 2000,
    deliverables: 'Design only',
    active: true,
  },
  {
    id: 'bc-br-2',
    category: 'Content & Creative',
    subcategory: 'Brand Creatives - Branding',
    name: 'Brochure (10 Pages)',
    unit: '10 Pages',
    price: 3500,
    deliverables: 'Design only',
    active: true,
  },
  {
    id: 'bc-br-3',
    category: 'Content & Creative',
    subcategory: 'Brand Creatives - Branding',
    name: 'Visiting Card',
    unit: 'Per Design',
    price: 250,
    deliverables: 'Front & back',
    active: true,
  },
  {
    id: 'bc-br-4',
    category: 'Content & Creative',
    subcategory: 'Brand Creatives - Branding',
    name: 'Letter Head',
    unit: 'Per Design',
    price: 350,
    deliverables: 'Single design',
    active: true,
  },
  {
    id: 'bc-br-5',
    category: 'Content & Creative',
    subcategory: 'Brand Creatives - Branding',
    name: 'Brand Book (Basic)',
    unit: 'Basic',
    price: 10000,
    priceRange: '5,000 - 10,000',
    deliverables: 'Brand guidelines (basic)',
    active: true,
  },
  {
    id: 'bc-br-6',
    category: 'Content & Creative',
    subcategory: 'Brand Creatives - Branding',
    name: 'Brand Book (Standard)',
    unit: 'Standard',
    price: 25000,
    priceRange: '20,000 - 25,000',
    deliverables: 'Extended brand guidelines',
    active: true,
  },
  {
    id: 'bc-br-7',
    category: 'Content & Creative',
    subcategory: 'Brand Creatives - Branding',
    name: 'Brand Book (Premium)',
    unit: 'Premium',
    price: 50000,
    deliverables: 'Complete brand system',
    active: true,
  },
  {
    id: 'bc-br-8',
    category: 'Content & Creative',
    subcategory: 'Brand Creatives - Branding',
    name: 'Hoardings',
    unit: 'Per Design',
    price: 5000,
    priceRange: '1,500 - 5,000',
    deliverables: 'Based on size & complexity',
    active: true,
  },
  {
    id: 'bc-br-9',
    category: 'Content & Creative',
    subcategory: 'Brand Creatives - Branding',
    name: 'Offline Poster',
    unit: 'Per Poster',
    price: 300,
    priceRange: '250 - 300',
    deliverables: 'Print ready file',
    active: true,
  },
  {
    id: 'pc-1',
    category: 'Content & Creative',
    subcategory: 'Performance Creatives',
    name: 'Ad Copies (Package)',
    unit: 'Per Package',
    price: 1200,
    deliverables: '1 static, 1 carousel multi-template, 1 video',
    active: true,
  },
  {
    id: 'pc-2',
    category: 'Content & Creative',
    subcategory: 'Performance Creatives',
    name: 'Ad Copy – Static Image',
    unit: 'Per Image',
    price: 300,
    deliverables: 'Single static creative',
    active: true,
  },
  {
    id: 'pc-3',
    category: 'Content & Creative',
    subcategory: 'Performance Creatives',
    name: 'Ad Copy – Carousel',
    unit: 'Per Carousel',
    price: 500,
    deliverables: 'Multi-template carousel',
    active: true,
  },
  {
    id: 'pc-4',
    category: 'Content & Creative',
    subcategory: 'Performance Creatives',
    name: 'Ad Copy – Video',
    unit: 'Per Video',
    price: 500,
    deliverables: 'Video creative (+₹300 for additional edits)',
    active: true,
  },
  {
    id: 'sv-1',
    category: 'Content & Creative',
    subcategory: 'Short Video Formats',
    name: 'YouTube Shorts / Reels',
    unit: 'Per Short',
    price: 500,
    deliverables: 'Up to 50 sec (Editing only)',
    active: true,
  },
  {
    id: 'ai-1',
    category: 'Content & Creative',
    subcategory: 'AI Production',
    name: 'AI Video (30s)',
    unit: '30 Seconds',
    price: 2000,
    deliverables: '1080x1080 / 1080x1920, 3-4 products',
    active: true,
  },
  {
    id: 'ai-2',
    category: 'Content & Creative',
    subcategory: 'AI Production',
    name: 'AI Video (15s)',
    unit: '15 Seconds',
    price: 1000,
    deliverables: '1080x1080 / 1080x1920, 1-2 products',
    active: true,
  },
  {
    id: 'ai-3',
    category: 'Content & Creative',
    subcategory: 'AI Production',
    name: 'AI Images',
    unit: 'Per Image',
    price: 350,
    deliverables: 'Lifestyle or Catalogue',
    active: true,
  },

  // --- 2. Marketing ---
  {
    id: 'mkt-org-smm-p1',
    category: 'Marketing',
    subcategory: 'Organic - Social Media Marketing',
    name: 'SMM Plan 1',
    unit: 'Per Month',
    price: 10000,
    deliverables: '5 Posts, 5 Stories, 5 Reels',
    description: 'Breakup: Posts (30% - ₹3,000), Stories (10% - ₹1,000), Reels (60% - ₹6,000).',
    active: true,
  },
  {
    id: 'mkt-org-smm-p2',
    category: 'Marketing',
    subcategory: 'Organic - Social Media Marketing',
    name: 'SMM Plan 2',
    unit: 'Per Month',
    price: 20000,
    deliverables: '12 Posts, 12 Stories, 12 Reels',
    description: 'Breakup: Posts (30% - ₹6,000), Stories (10% - ₹2,000), Reels (60% - ₹12,000).',
    active: true,
  },
  {
    id: 'mkt-org-smm-p3',
    category: 'Marketing',
    subcategory: 'Organic - Social Media Marketing',
    name: 'SMM Plan 3',
    unit: 'Per Month',
    price: 30000,
    deliverables: '20 Posts, 20 Stories, 20 Reels',
    description: 'Breakup: Posts (30% - ₹9,000), Stories (10% - ₹3,000), Reels (60% - ₹18,000).',
    active: true,
  },
  {
    id: 'mkt-org-smm-flex',
    category: 'Marketing',
    subcategory: 'Organic - Social Media Marketing',
    name: 'Flexible SMM Plan',
    unit: 'Custom',
    price: 1000,
    deliverables: 'Custom combination of content.',
    description: 'Pricing logic: Posts 30%, Stories 10%, Reels 60%. Breakdown will be shown in final invoice.',
    active: true,
  },
  {
    id: 'mkt-org-search-web-basic-manual',
    category: 'Marketing',
    subcategory: 'Organic - Search Media',
    name: 'Website SEO - Basic (Manual)',
    unit: 'Per Month',
    price: 10000,
    deliverables: 'Keyword research, On-page optimization, Technical SEO check.',
    description: 'Fully handled by the team.',
    active: true,
  },
  {
    id: 'mkt-org-search-web-basic-ai',
    category: 'Marketing',
    subcategory: 'Organic - Search Media',
    name: 'Website SEO - Basic (AI-Agent)',
    unit: 'Per Month',
    price: 5000,
    deliverables: 'Keyword research, On-page optimization, Technical SEO check.',
    description: 'AI-driven execution + expert review. 50% savings included!',
    active: true,
  },

  // --- 3. Ecommerce: Rietail ---
  {
    id: 'ecom-ri-web-cat',
    category: 'Ecommerce',
    subcategory: 'Rietail',
    name: 'Enquiry & Catalog Website',
    unit: 'Setup + Monthly',
    price: 10000,
    monthlyPrice: 499,
    deliverables: 'Custom Catalog sharing & Enquiry forms.',
    description: 'Includes One-time Installation and Monthly Subscription.',
    active: true,
  },
  {
    id: 'ecom-ri-web-order',
    category: 'Ecommerce',
    subcategory: 'Rietail',
    name: 'Booking & Order Website',
    unit: 'Setup + Monthly',
    price: 25000,
    monthlyPrice: 499,
    deliverables: 'Full e-commerce booking & order processing.',
    description: 'Includes One-time Installation and Monthly Subscription.',
    active: true,
  },
  {
    id: 'ecom-ri-web-dist',
    category: 'Ecommerce',
    subcategory: 'Rietail',
    name: 'Booking & Order Website + Distributor Panel',
    unit: 'Setup + Monthly',
    price: 40000,
    monthlyPrice: 1499,
    deliverables: 'Order processing + Distributor management portal.',
    description: 'Includes One-time Installation and Monthly Subscription.',
    active: true,
  },
  {
    id: 'ecom-ri-app-android',
    category: 'Ecommerce',
    subcategory: 'Rietail',
    name: 'Android Mobile Application',
    unit: 'Setup + Monthly',
    price: 25000,
    monthlyPrice: 499,
    deliverables: 'Native Android application with store deployment.',
    active: true,
  },
  {
    id: 'ecom-ri-app-ios',
    category: 'Ecommerce',
    subcategory: 'Rietail',
    name: 'iOS Mobile Application',
    unit: 'Setup + Monthly',
    price: 40000,
    monthlyPrice: 499,
    deliverables: 'Native iOS application with store deployment.',
    active: true,
  },
  {
    id: 'ecom-ri-comb-web-and',
    category: 'Ecommerce',
    subcategory: 'Rietail',
    name: 'Combined: Website + Android App',
    unit: 'Monthly Subscription',
    price: 0,
    monthlyPrice: 999,
    deliverables: 'Unified Web & Android maintenance (Installation extra).',
    active: true,
  },
  {
    id: 'ecom-ri-comb-web-all',
    category: 'Ecommerce',
    subcategory: 'Rietail',
    name: 'Combined: Website + Android + iOS App',
    unit: 'Monthly Subscription',
    price: 0,
    monthlyPrice: 1499,
    deliverables: 'Full Web, Android & iOS maintenance (Installation extra).',
    active: true,
  },
  {
    id: 'ecom-ri-comb-enterprise',
    category: 'Ecommerce',
    subcategory: 'Rietail',
    name: 'Combined: Website + Apps + Distributor',
    unit: 'Monthly Subscription',
    price: 0,
    monthlyPrice: 1999,
    deliverables: 'Omnichannel suite + Distributor Panel maintenance.',
    active: true,
  },
  {
    id: 'ecom-ri-ent-dist',
    category: 'Ecommerce',
    subcategory: 'Rietail',
    name: 'Distributor Enterprise Plan',
    unit: 'One-time',
    price: 100000,
    deliverables: 'Enterprise scale Supply Chain management system.',
    active: true,
  },
  {
    id: 'ecom-ri-setup',
    category: 'Ecommerce',
    subcategory: 'Rietail',
    name: 'First-Time Setup Fee',
    unit: 'One-time',
    price: 10000,
    deliverables: 'Account setup, cloud provisioning, and initial configuration.',
    active: true,
  },
  {
    id: 'ecom-ri-erp',
    category: 'Ecommerce',
    subcategory: 'Rietail',
    name: 'ERP Integration Fee',
    unit: 'One-time',
    price: 5000,
    deliverables: 'Standard API integration with external ERP systems.',
    active: true,
  },
  {
    id: 'ecom-ri-loy-t1',
    category: 'Ecommerce',
    subcategory: 'Rietail',
    name: 'Loyalty Tier 1 (Add-on)',
    unit: 'Setup + Monthly',
    price: 10000,
    monthlyPrice: 8900,
    deliverables: 'Includes Magic Store + Reward Points + Coupons.',
    description: 'Includes US$100 monthly subscription and ₹10,000 one-time setup.',
    active: true,
  },
  {
    id: 'ecom-ri-loy-t2',
    category: 'Ecommerce',
    subcategory: 'Rietail',
    name: 'Loyalty Tier 2 (Add-on)',
    unit: 'Setup + Monthly',
    price: 10000,
    monthlyPrice: 13350,
    deliverables: 'Includes Magic Store + Reward Points + Coupons + Scheme Module.',
    description: 'Includes US$150 monthly subscription and ₹10,000 one-time setup.',
    active: true,
  },

  // --- 4. Technology ---
  {
    id: 'tech-svc-1',
    category: 'Technology',
    subcategory: 'Tech Services',
    name: 'Technical Services / Agent Services',
    unit: 'Per Hour',
    price: 800,
    deliverables: 'Expert technical consulting and agent-based task execution.',
    active: true,
  },
  {
    id: 'tech-static-1',
    category: 'Technology',
    subcategory: 'Static Website Services',
    name: 'Standard Website Development',
    unit: 'Per Page',
    price: 3000,
    deliverables: 'High-quality static page development and design.',
    active: true,
  },
  {
    id: 'tech-shopify-1',
    category: 'Technology',
    subcategory: 'Shopify Services',
    name: 'Shopify Website / Mobile Integration',
    unit: 'Project',
    price: 0,
    deliverables: 'Custom integration for Shopify storefronts and mobile sync.',
    description: 'Project-based custom pricing depending on complexity.',
    active: true,
  },
  {
    id: 'tech-hosting-1',
    category: 'Technology',
    subcategory: 'Hosting & Deployment',
    name: 'Hosting & Deployment Charges',
    unit: 'Per Year',
    price: 3000,
    deliverables: 'Cloud hosting setup, deployment automation, and maintenance.',
    description: 'Pricing is usage-based.',
    active: true,
  },
];

export const INITIAL_CLIENT_INFO: ClientInfo = {
  companyName: '',
  contactPerson: '',
  email: '',
  phone: '',
  address: '',
  date: new Date().toISOString().split('T')[0],
};

export const INITIAL_PROPOSAL_CONFIG: ProposalConfig = {
  headerTitle: 'PROJECT PROPOSAL',
  contactEmail: 'marketing@forwardworkx.com',
  termsAndConditions: [
    '1. Payment Terms: 50% advance, 50% upon completion.',
    '2. Validity: This proposal is valid for 15 days from the date of issue.',
    '3. All creative rights remain with ForwardWorkx until full payment is received.'
  ]
};
